### PR TITLE
implemented a quick login check script to include in the header

### PR DESCRIPTION
**Pull request by s3666874**
Quick PR to add a login check to the header of all the files. It doesn't persist any form variables but we can add this in later if we want.

### CODE REVIEW

**Comment by jaz998** [comment]
@s3666874, should we change the codes to check booking.php and bookingWMap.php as well? The reason I'm asking is that  the booking2.php takes the car ID via post from either the booking.php or bookingWMap.php. If we do it the way it currently is, user will select a car, then would be asked to login (if not already), then the car ID selected will be lost and the user needs to repeat the whole process again.

**Comment by s3666874** [comment]
@jaz998, yep that make sense. So just to confirm, the pages we want to restrict are:

booking.php
booking2.php
bookingWMap.php
bookingcheckout.php

We can always add to this array later.

**Comment by jaz998** [comment]
@s3666874, yes that’s right.

**Comment by s3666874** [comment]
@jaz998 done

**Pull request merged**
